// <auto-generated />
using System;
using DrTaabodi.Data.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrTaabodi.Data.Migrations
{
    [DbContext(typeof(DrTaabodiDbContext))]
    [Migration("20211223180526_base")]
    partial class @base
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DrTaabodi.Data.Models.FileSystemTbl", b =>
                {
                    b.Property<Guid>("FileSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compilation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileFolderPath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasChilds")
                        .HasColumnType("bit");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageRuntimeVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFile")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastWriteTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileSystemId");

                    b.HasIndex("ParentId");

                    b.ToTable("FileSystem");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.MetaTbl", b =>
                {
                    b.Property<Guid>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetaKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PstTblPstId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MetaId");

                    b.HasIndex("PstTblPstId");

                    b.ToTable("MetaTbl");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PostCategoryTbl", b =>
                {
                    b.Property<Guid>("PostCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedData")
                        .HasColumnType("datetime2");

                    b.HasKey("PostCategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("PostCategoryTbl");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PostTypeTbl", b =>
                {
                    b.Property<Guid>("PostTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedData")
                        .HasColumnType("datetime2");

                    b.HasKey("PostTypeId");

                    b.HasIndex("ParentId");

                    b.ToTable("PostTypeTbl");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PstTbl", b =>
                {
                    b.Property<Guid>("PstId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PstContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PstDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PstTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedData")
                        .HasColumnType("datetime2");

                    b.HasKey("PstId");

                    b.HasIndex("ParentId");

                    b.ToTable("PstTbl");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.QnATbl", b =>
                {
                    b.Property<Guid>("QnAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<DateTime>("UpdatedData")
                        .HasColumnType("datetime2");

                    b.HasKey("QnAId");

                    b.ToTable("QnATbl");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.UsrTbl", b =>
                {
                    b.Property<Guid>("UsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassCode")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedData")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsrEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsrFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsrNickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsrStatus")
                        .HasColumnType("int");

                    b.HasKey("UsrId");

                    b.ToTable("UsrTbl");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.WebsiteOptionsTbl", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OptionId");

                    b.ToTable("WebsiteOptionsTbls");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PostCategoryTblPstTbl", b =>
                {
                    b.Property<Guid>("PostCategoryTablePostCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostTablePstId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostCategoryTablePostCategoryId", "PostTablePstId");

                    b.HasIndex("PostTablePstId");

                    b.ToTable("PostCategoryTblPstTbl");
                });

            modelBuilder.Entity("PostTypeTblPstTbl", b =>
                {
                    b.Property<Guid>("PostTablePstId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostTypeTablePostTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostTablePstId", "PostTypeTablePostTypeId");

                    b.HasIndex("PostTypeTablePostTypeId");

                    b.ToTable("PostTypeTblPstTbl");
                });

            modelBuilder.Entity("PstTblUsrTbl", b =>
                {
                    b.Property<Guid>("PostTablePstId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserTableUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostTablePstId", "UserTableUsrId");

                    b.HasIndex("UserTableUsrId");

                    b.ToTable("PstTblUsrTbl");
                });

            modelBuilder.Entity("QnATblUsrTbl", b =>
                {
                    b.Property<Guid>("QuestionAndAnswerTableQnAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserTableUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionAndAnswerTableQnAId", "UserTableUsrId");

                    b.HasIndex("UserTableUsrId");

                    b.ToTable("QnATblUsrTbl");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.FileSystemTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.FileSystemTbl", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.MetaTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.PstTbl", null)
                        .WithMany("MetaTable")
                        .HasForeignKey("PstTblPstId");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PostCategoryTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.PostCategoryTbl", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PostTypeTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.PostTypeTbl", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PstTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.PstTbl", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostCategoryTblPstTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.PostCategoryTbl", null)
                        .WithMany()
                        .HasForeignKey("PostCategoryTablePostCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrTaabodi.Data.Models.PstTbl", null)
                        .WithMany()
                        .HasForeignKey("PostTablePstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostTypeTblPstTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.PstTbl", null)
                        .WithMany()
                        .HasForeignKey("PostTablePstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrTaabodi.Data.Models.PostTypeTbl", null)
                        .WithMany()
                        .HasForeignKey("PostTypeTablePostTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PstTblUsrTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.PstTbl", null)
                        .WithMany()
                        .HasForeignKey("PostTablePstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrTaabodi.Data.Models.UsrTbl", null)
                        .WithMany()
                        .HasForeignKey("UserTableUsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QnATblUsrTbl", b =>
                {
                    b.HasOne("DrTaabodi.Data.Models.QnATbl", null)
                        .WithMany()
                        .HasForeignKey("QuestionAndAnswerTableQnAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrTaabodi.Data.Models.UsrTbl", null)
                        .WithMany()
                        .HasForeignKey("UserTableUsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.FileSystemTbl", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PostCategoryTbl", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PostTypeTbl", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DrTaabodi.Data.Models.PstTbl", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MetaTable");
                });
#pragma warning restore 612, 618
        }
    }
}
